Make expect_newline show error in the right place
Beforehand, on error, it would show the error at the state that's after the non-newline
token, which is wrong.

For example:
Error: expected newline
log log
       ^

Now it shows the error before the wrong token.

For example:
Error: expected newline
log log
    ^